### ISSUE TITLE
Не загружается конфигурация из исходников

### ISSUE THREAD

**Issue by Serg2000Mr** [progtb/ptb_ssl#1]
При загрузке конфигурации из файлов папки src в конфигураторе ошибка: Версия формата загружаемого файла \src\Ext\MainSectionCommandInterface.xml  отличается от версии формата ранее загруженных файлов. Версия формата файла - "2.13", версия формата ранее загруженных файлов - "2.16"

**Comment by vandalsvq** [comment]
Обновил выгрузку. Версия 1.1.0.4 fx4
@Serg2000Mr как проверишь напиши.
